name: CD
on:
  workflow_dispatch:
    inputs:
      runE2eTests:
        description: Run E2E tests
        type: boolean
        default: false
  push:
    branches: ["main"]

jobs:
  update-asg:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update ASG desired capacity
        run: |
          ASG_NAME="terraform-20250121185357556700000002"
          DESIRED_CAPACITY=1
          ASG_EXISTS=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --query 'AutoScalingGroups[0].AutoScalingGroupName' --output text)
          if [ "$ASG_EXISTS" == "$ASG_NAME" ]; then
            aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --desired-capacity $DESIRED_CAPACITY
          else
            echo "ASG $ASG_NAME not found"
          fi

      - name: Update ASG2 desired capacity
        run: |
          ASG_NAME="terraform-20250121190400418200000002"
          DESIRED_CAPACITY=1
          ASG_EXISTS=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $ASG_NAME --query 'AutoScalingGroups[0].AutoScalingGroupName' --output text)
          if [ "$ASG_EXISTS" == "$ASG_NAME" ]; then
            aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --desired-capacity $DESIRED_CAPACITY
          else
            echo "ASG $ASG_NAME not found"
          fi
