name: CD
on:
  workflow_dispatch:
    inputs:
      runE2eTests:
        description: Run E2E tests
        type: boolean
        default: false
  push:
    branches: ["main"]

jobs:
  update-asg:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: List Auto Scaling Groups
        id: list-asgs
        run: aws autoscaling describe-auto-scaling-groups

      - name: Update ASG desired capacity
        if: contains(steps.list-asgs.outputs.stdout, 'example-asg')
        run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name example-asg --desired-capacity 1

      - name: Update ASG2 desired capacity
        if: contains(steps.list-asgs.outputs.stdout, 'example-asg2')
        run: aws autoscaling update-auto-scaling-group --auto-scaling-group-name example-asg2 --desired-capacity 1
